export const shopTypes = {
  FETCH_COLLECTIONS_REQUEST: "FETCH_COLLECTIONS_REQUEST",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTIONS_FAILURE",
};
