export const userTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  
  GOOGLE_SIGN_IN_REQUEST: "GOOGLE_SIGN_IN_REQUEST",
  EMAIL_SIGN_IN_REQUEST: "EMAIL_SIGN_IN_REQUEST",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",

  CHECK_USER_SESSION: "CHECK_USER_SESSION",

  SIGN_OUT_REQUEST: "SIGN_OUT_REQUEST",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",

  SIGN_UP_REQUEST: "SIGN_UP_REQUEST",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
};
