export const userTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  GOOGLE_SIGN_IN_REQUEST: "GOOGLE_SIGN_IN_REQUEST",
  EMAIL_SIGN_IN_REQUEST: "EMAIL_SIGN_IN_REQUEST",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
};
